<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__1</name>
   <tag></tag>
   <elementGuidId>2951d240-9239-442d-87e4-cdc62c216d47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='navbar']/ul/li[4]/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>250d5b19-29b5-44c8-9da9-b14c87e6f7b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Home/Complain</value>
      <webElementGuid>fef38c4a-90c1-478a-a317-43db434645a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>sub-menu</value>
      <webElementGuid>0ab55e93-e10a-4d2a-b4ea-d4be9d5a22db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>اضافة شكوي جديده</value>
      <webElementGuid>3940479e-9bd7-4934-b050-4dd25ac18e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar&quot;)/ul[@class=&quot;menu&quot;]/li[@class=&quot;menu-item menu-item-child&quot;]/ul[@class=&quot;sub-menu&quot;]/li[@class=&quot;menu-item&quot;]/a[1]</value>
      <webElementGuid>c88ade4c-8d4c-4b58-b4df-04f271a570ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='navbar']/ul/li[4]/ul/li[4]/a</value>
      <webElementGuid>801e4296-536e-4120-ab99-9cf56767507d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'اضافة شكوي جديده')]</value>
      <webElementGuid>1ce1e335-eb4f-4677-ab7f-3eea96185f5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الشكاوي'])[1]/following::a[1]</value>
      <webElementGuid>c91ac6e9-6767-4bc0-8319-0d0ef73ceb3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اضافة تمليك جديد'])[1]/following::a[2]</value>
      <webElementGuid>4baf2283-1f5c-4af0-86d4-5be570a50eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='المشروعات'])[1]/preceding::a[1]</value>
      <webElementGuid>203f550e-7c2b-478e-8edc-080ff9c1f470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='مزادات'])[1]/preceding::a[2]</value>
      <webElementGuid>015853f2-e6b9-4bd2-9979-9c804696825d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='اضافة شكوي جديده']/parent::*</value>
      <webElementGuid>07962bea-2909-4f34-b4cf-1a0197201293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Home/Complain')]</value>
      <webElementGuid>3ba4c32a-1bf6-48f8-acbe-6d53d247e75d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li[4]/a</value>
      <webElementGuid>3bcff97c-01b3-4d03-b2af-01ffab0e5468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Home/Complain' and (text() = 'اضافة شكوي جديده' or . = 'اضافة شكوي جديده')]</value>
      <webElementGuid>97262402-1e67-48d4-a802-e161b23b2615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='logoutForm']/li[2]/a</value>
      <webElementGuid>b57cdf14-c6d6-4622-a5a6-e2fb0c758160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'خروج')]</value>
      <webElementGuid>b5d84a61-782c-45af-bb08-3b3db5197023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='نسخه تجريبيه'])[1]/following::a[1]</value>
      <webElementGuid>845f91d9-f31c-4484-be7c-1b3bdaea5bb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[1]/following::a[1]</value>
      <webElementGuid>622b263a-5b27-4442-bd1b-b4aa949e25c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='بيانات الحساب'])[1]/preceding::a[1]</value>
      <webElementGuid>c0a57b6d-dd88-4e50-b88d-1f16ffeacf49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='مرحبا :'])[1]/preceding::a[2]</value>
      <webElementGuid>2deb88ea-6572-4e54-af78-b13619423d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='خروج']/parent::*</value>
      <webElementGuid>8fd31772-8199-4bf7-bc1e-15ff6fe0eb94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:document.getElementById('logoutForm').submit()&quot;)]</value>
      <webElementGuid>7381eaff-334e-47cf-bb3f-d2e2791a34b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/li[2]/a</value>
      <webElementGuid>57d1a274-3fa9-4e1f-a196-13b0fc114b28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:document.getElementById(&quot; , &quot;'&quot; , &quot;logoutForm&quot; , &quot;'&quot; , &quot;).submit()&quot;) and (text() = 'خروج' or . = 'خروج')]</value>
      <webElementGuid>23daba0a-1ae6-40a3-9705-1e7f2bdcd1db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='navbar']/ul/li[4]/a</value>
      <webElementGuid>a431a836-1c30-4fff-93b2-b61d7bdb8de9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'الخدمات الألكترونية')]</value>
      <webElementGuid>a69c26cb-763a-4d6d-8751-c56bae21d565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ميديا'])[1]/following::a[1]</value>
      <webElementGuid>090d7adf-4daf-4b67-9416-0a84b80a64d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اخبار الهيئة'])[1]/following::a[2]</value>
      <webElementGuid>f198065a-39cd-4334-b175-30cb0077f3d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='طلبات التمليك'])[1]/preceding::a[1]</value>
      <webElementGuid>52fd070c-f02c-492d-9026-1c8290045d33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اضافة تمليك جديد'])[1]/preceding::a[2]</value>
      <webElementGuid>89ded68e-580a-454e-9b56-2576f908c73d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='الخدمات الألكترونية']/parent::*</value>
      <webElementGuid>e730dc83-3293-4283-831a-558657c1f3a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[3]</value>
      <webElementGuid>0753d63e-ef3e-4c94-a44e-e90c3d40b328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>fca6534a-2e2e-4a1a-b56e-c110f52bf3d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'الخدمات الألكترونية' or . = 'الخدمات الألكترونية')]</value>
      <webElementGuid>3661eec5-eb02-4f2b-83b0-ea1c44f1008a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
