<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__CaptchaInputText</name>
   <tag></tag>
   <elementGuidId>a00e7c74-3432-4fde-b6c6-18bff1c1b872</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CaptchaInputText']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CaptchaInputText</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>83f29ee1-ead2-4924-8f1a-e0e3ab75eb3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b3b44740-a15d-424a-81cf-111f1a3d000e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>198b2bd7-f3b5-4e96-bfb3-dc5c22a8aef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e88fb9bc-f4ac-45fb-8ebd-64f190b01026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>هذا الحقل مطلوب</value>
      <webElementGuid>5a8756ea-2749-4e67-8505-b4b71578a169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CaptchaInputText</value>
      <webElementGuid>5de357a0-72da-4a11-b533-be680e9d8518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CaptchaInputText</value>
      <webElementGuid>ba727280-e23a-40e6-a1d5-e96c26f94b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>974a5f85-fc10-4335-b7d8-c089ab7646d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CaptchaInputText&quot;)</value>
      <webElementGuid>c217270e-0b68-4179-9c23-3f522a724e57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CaptchaInputText']</value>
      <webElementGuid>adcb07d0-8ca3-4d78-b7f0-921b18401a0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='fromCaptcha']/div[7]/input[2]</value>
      <webElementGuid>5d53ce45-9a81-464d-a594-f6bbd09949bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input[2]</value>
      <webElementGuid>2f5e4712-62a0-45fa-8c6a-b1daa2e6fb63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CaptchaInputText' and @name = 'CaptchaInputText' and @type = 'text']</value>
      <webElementGuid>816a0d96-079b-407e-b14c-90016ced431e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
