<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__button button-block</name>
   <tag></tag>
   <elementGuidId>c1417329-1bfd-461e-b321-8d838e8797d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login > form.form-horizontal > input.button.button-block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='دخول']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>765c1b44-51ac-4b9d-b990-f476b800d0fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>0a8186c3-ff9f-4b8a-9699-752ff74092a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button-block</value>
      <webElementGuid>e02ca29c-be68-4187-af66-5fa03eb9134b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>دخول</value>
      <webElementGuid>f3ea8d55-6526-482b-a5d4-75c97e64825d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login&quot;)/form[@class=&quot;form-horizontal&quot;]/input[@class=&quot;button button-block&quot;]</value>
      <webElementGuid>a910c8b5-ec85-41fc-a7ae-6d2fa805d305</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='دخول']</value>
      <webElementGuid>23f0d4f8-369e-4954-b59b-fef1ea64b008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login']/form/input[2]</value>
      <webElementGuid>de2bcca9-1436-4228-96cf-0e0df24ef898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/input[2]</value>
      <webElementGuid>7c4ca183-ab69-4909-85e4-748b9d2a1624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>20fa7ac9-9333-495c-a720-4e5caec99ca4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
