<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__button button-block_1</name>
   <tag></tag>
   <elementGuidId>c559537f-7924-4621-b137-ffb17f4fda54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login > form.form-horizontal > input.button.button-block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='دخول']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>862bfb18-1872-4078-a6d0-3809ee680f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>61c16316-74d0-45e5-b79a-416c98c240ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button-block</value>
      <webElementGuid>bfeaeaaf-f73a-42c9-be4b-a8e5e9903421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>دخول</value>
      <webElementGuid>9170c399-ae85-47b3-acbd-63c14f250b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login&quot;)/form[@class=&quot;form-horizontal&quot;]/input[@class=&quot;button button-block&quot;]</value>
      <webElementGuid>41b5211a-58ac-4207-b74a-ae0c7ee68167</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='دخول']</value>
      <webElementGuid>0b2d43c1-5a44-4abb-bd8f-fa4e152e809d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login']/form/input[2]</value>
      <webElementGuid>65619763-315f-478a-a9ca-4461a760a757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/input[2]</value>
      <webElementGuid>8a7cbe13-6b00-4ee9-9dfc-4d98478666cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>92202c58-194e-4ef5-a8d7-fd6900c8b8c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
