<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>login</name>
   <tag></tag>
   <elementGuidId>57c35c89-2550-4fcc-ad17-1a9f16db5c69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.tab.active > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='exampleModal']/div/div/div/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b4f37afd-e06a-42a3-8aec-2b51ac17fccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#login</value>
      <webElementGuid>3cd11830-0e04-4e36-b39c-4d603320cac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>تسجيل دخول</value>
      <webElementGuid>a5ebdd38-4050-407f-bced-fbde24ec6991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exampleModal&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;form&quot;]/ul[@class=&quot;tab-group&quot;]/li[@class=&quot;tab active&quot;]/a[1]</value>
      <webElementGuid>7e7ee443-8a91-4e5d-8090-958b25abcd90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='exampleModal']/div/div/div/div/ul/li[2]/a</value>
      <webElementGuid>8f98abd6-364e-4a31-af43-0b2486aed3f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'تسجيل دخول')]</value>
      <webElementGuid>8b005956-c19f-4779-9358-5090dab78f5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='مستخدم جديد'])[1]/following::a[1]</value>
      <webElementGuid>5c67f0df-a67d-493e-9722-c884470c47ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2021 -جميع الحقوق محفوظة لهيئه الأوقاف المصرية'])[1]/following::a[2]</value>
      <webElementGuid>556313a4-d292-4b83-8fc3-6979cf059014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::a[1]</value>
      <webElementGuid>f75b367e-229e-4496-962f-864b608d8ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#login')]</value>
      <webElementGuid>2710f8b0-b14b-40b9-ac3a-dc9152fac049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/div/div/div/div/div/ul/li[2]/a</value>
      <webElementGuid>02f341c9-5a94-44d4-a7de-65e04b7fe07f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#login' and (text() = 'تسجيل دخول' or . = 'تسجيل دخول')]</value>
      <webElementGuid>911ce09f-7bae-4cd4-84ec-d14bf17c0aad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
