<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Captcha_CaptchaImage</name>
   <tag></tag>
   <elementGuidId>4b75d221-d01e-4399-bb2b-342bc25a729b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='CaptchaImage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CaptchaImage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>65249047-6b32-46e2-81db-fa02bd72a852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CaptchaImage</value>
      <webElementGuid>306caed5-c9cc-4ce8-9a85-5d69bcdd308a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/DefaultCaptcha/Generate?t=967e6c48847643b8a09d947c92a63401</value>
      <webElementGuid>8567be32-9876-4615-8869-bdab7a9900f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CaptchaImage&quot;)</value>
      <webElementGuid>dbbe6b2b-991b-4acd-bbe3-044ba5f24e4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='CaptchaImage']</value>
      <webElementGuid>097bef12-4cdf-4aa3-8116-28fa50c881db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='fromCaptcha']/div[7]/img</value>
      <webElementGuid>f97c65fc-ff50-4444-a036-98e747a2be75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/img</value>
      <webElementGuid>24a51d77-eec1-42a4-873a-710785ca4cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'CaptchaImage' and @src = '/DefaultCaptcha/Generate?t=967e6c48847643b8a09d947c92a63401']</value>
      <webElementGuid>717f5209-56b1-4145-90bd-99a06cb324e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
