<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__PersonsIDNo</name>
   <tag></tag>
   <elementGuidId>d6fccfe8-1202-4f66-ad75-fc6723a3871f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PersonsIDNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PersonsIDNo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fdf4bf9e-f9b4-4923-99b5-9ba7a59a84b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c060768e-eb6a-4bda-a3b0-073ee3de64c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PersonsIDNo</value>
      <webElementGuid>b3e7b86a-57e1-487e-a0b0-7722773168ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PersonsIDNo</value>
      <webElementGuid>67a31b1d-441d-4ef7-a79b-bee2a414e48b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>رقم تحقيق الشخصية</value>
      <webElementGuid>f34657be-05e4-441e-aff5-bd1ae5e80cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>80d7dbeb-bd74-4f89-bf1b-02e2e7acc895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PersonsIDNo&quot;)</value>
      <webElementGuid>427e271b-bae9-44a1-b6df-b33d796f1b8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PersonsIDNo']</value>
      <webElementGuid>05eaf5ec-433c-47fa-8c6f-f82728a1848d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Persons']/div[4]/input</value>
      <webElementGuid>26ee00df-7764-4874-a405-87ed6d4430e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>a2202d0f-1e9f-4e70-a578-6391cf59df3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PersonsIDNo' and @name = 'PersonsIDNo' and @placeholder = 'رقم تحقيق الشخصية' and @type = 'text']</value>
      <webElementGuid>691e94be-4757-416c-9d4d-137413bf76d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
