<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__StatusOfPayment</name>
   <tag></tag>
   <elementGuidId>41a6f73a-34fa-4cfd-ac46-aa84d388fda3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;StatusOfPayment&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='StatusOfPayment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24e3450d-2ab3-4b1b-bd7e-ffde3acca747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ac27227d-fb1a-44d6-95bc-4f4b3436cc5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>724120bc-355a-4d8b-9a1f-89424389711a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>StatusOfPayment</value>
      <webElementGuid>eca8fd1f-ae54-40b0-a8c7-e99d11adb745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>الموقف من السداد للايجار</value>
      <webElementGuid>9600588e-a9e7-4798-8512-d04c791a5e0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[@class=&quot;col-lg-8&quot;]/div[@class=&quot;box_general write_review&quot;]/form[1]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>a69f90ca-b30b-4a5e-bb7f-5d11c01ebc42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='StatusOfPayment']</value>
      <webElementGuid>d84ec6ae-cf8b-4e2b-bf90-77b33274ed4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/div/form/div[7]/div[2]/div[2]/div/div/input</value>
      <webElementGuid>07d7627a-5c80-45dc-89b2-fed7e84c06fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/input</value>
      <webElementGuid>7fa9d66e-56e1-43d7-ad73-8101f7b4c989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'StatusOfPayment' and @placeholder = 'الموقف من السداد للايجار']</value>
      <webElementGuid>c822fb39-b0c0-4637-a26c-a8a9bf500ee2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
