<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__PersonsBuildingNo</name>
   <tag></tag>
   <elementGuidId>62adf29c-5b3a-4af4-90ce-e9996f2e05ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PersonsBuildingNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PersonsBuildingNo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>68b5fd77-b7f6-4abd-bcdd-81731bc25505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>900625a9-7d92-45e7-b180-cec9ead8c97d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PersonsBuildingNo</value>
      <webElementGuid>d94cc384-9258-4f32-9a99-3fc47182788e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PersonsBuildingNo</value>
      <webElementGuid>13131ed2-f84c-484c-b08e-2f4d445e3cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>رقم المبنى</value>
      <webElementGuid>228892e8-2f64-4d92-997f-5e4f2b9e3a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f60735e3-9179-4c97-8de2-4d06da1f8ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PersonsBuildingNo&quot;)</value>
      <webElementGuid>d672d7df-1e56-4e9a-b3bd-b308197cfdef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PersonsBuildingNo']</value>
      <webElementGuid>4c090acc-e6ef-49a5-b20d-719fdb4420f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Persons']/div[6]/input</value>
      <webElementGuid>ddf094ea-4171-4fb3-9631-2d9591dd9a85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>2c37c358-00c6-4922-bb31-389b36f787ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PersonsBuildingNo' and @name = 'PersonsBuildingNo' and @placeholder = 'رقم المبنى' and @type = 'text']</value>
      <webElementGuid>8858818f-887f-439d-a361-9202848088da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
