<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__PersonsApartNo</name>
   <tag></tag>
   <elementGuidId>ca16e1f1-cc35-4c92-b8c3-1331a6744e11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PersonsApartNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PersonsApartNo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c4e98705-3e35-4700-a514-f87ac31a211d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>350f3d64-55fd-42d6-a700-83b86efc2674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PersonsApartNo</value>
      <webElementGuid>99863044-a4d9-42db-9bd1-3cbb273df2d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PersonsApartNo</value>
      <webElementGuid>658843fe-7d07-4fd3-8232-c5966fd9fc56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>رقم الشقة</value>
      <webElementGuid>a1d44b59-4500-493a-8371-e286d9cf7504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5dd6b3e8-2f30-4830-b49d-999129283bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PersonsApartNo&quot;)</value>
      <webElementGuid>e5aa0cee-89a2-47e2-b2b8-c21fbe766df7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PersonsApartNo']</value>
      <webElementGuid>e176e177-2186-4c22-b595-056dfddc32dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Persons']/div[8]/input</value>
      <webElementGuid>1e4eb811-5334-4bbe-93ab-f7657827be41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[8]/input</value>
      <webElementGuid>0dd69b03-b56e-41eb-8e04-893bb82e9cfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PersonsApartNo' and @name = 'PersonsApartNo' and @placeholder = 'رقم الشقة' and @type = 'text']</value>
      <webElementGuid>c41a6f98-84a4-4bb0-8dcb-4f2699c6bac6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
