<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ComplainType</name>
   <tag></tag>
   <elementGuidId>aca666b9-af1e-4fc6-9e3b-36af05b3df21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ComplainType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ComplainType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>51401292-409f-4a26-a564-407aed2ca3b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ComplainType</value>
      <webElementGuid>6c944682-1c62-4dd6-a467-decd366217cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ComplainType</value>
      <webElementGuid>5518b7ff-3728-4b78-9bd5-5f4d9312522d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>4b98c363-3069-4c46-89a0-a5cb36d946a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>dfa6c17e-5b14-4ccb-b40c-d998b44105b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[@class=&quot;col-lg-8&quot;]/div[@class=&quot;box_general write_review&quot;]/form[1]/div[@class=&quot;form-inline&quot;]/div[@class=&quot;form-check form-check-inline&quot;]/input[@id=&quot;ComplainType&quot;]</value>
      <webElementGuid>5643c41a-8b00-486a-a28d-5bafdfd89569</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ComplainType']</value>
      <webElementGuid>459763af-afe1-4e1e-8c67-ca4307bed1b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/div/form/div[3]/div/input</value>
      <webElementGuid>85121cc1-1a56-45b7-a4bf-50eeb4c5b443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>622a307b-d28e-4762-b050-247c02d3bd37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ComplainType' and @name = 'ComplainType' and @type = 'radio']</value>
      <webElementGuid>2a7b6bf5-4551-403e-9609-85f9f2f9ce71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
