<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__PhoneNo</name>
   <tag></tag>
   <elementGuidId>b8229444-f686-4927-b119-2edea05d4e53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PhoneNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PhoneNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c21c1dd6-849f-44bc-82e8-93d67d11e051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4712509b-4009-48fb-879f-154d8afb9bba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>67d83112-3d19-492b-9695-f1fbcf49fe93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>من فضلك ادخل رقم الهاتف</value>
      <webElementGuid>3fa26b00-ea24-456d-b24b-6aacc0dfeac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PhoneNo</value>
      <webElementGuid>de37cf86-3c0d-4ee9-ac3f-96d215c159d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PhoneNo</value>
      <webElementGuid>80c0419e-ecee-4a78-a781-8fa5da8dca99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>رقم الهاتف</value>
      <webElementGuid>a869f337-f147-41fe-93cb-9b31b9f7dbfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>00b895ef-67f8-4bdb-9673-1d9944b80932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PhoneNo&quot;)</value>
      <webElementGuid>d5d37a50-4cae-4b06-b5c5-f5fd0fdf61af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PhoneNo']</value>
      <webElementGuid>00be11f8-0da5-479d-83fb-95cce4859dd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/div/form/div[9]/input</value>
      <webElementGuid>2bd8025c-b512-44d1-9922-ace5f755b6c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/input</value>
      <webElementGuid>688767f9-6530-4db1-9911-6c3dd3dd860f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PhoneNo' and @name = 'PhoneNo' and @placeholder = 'رقم الهاتف' and @type = 'text']</value>
      <webElementGuid>6d5a702b-abbf-43d8-af21-7f458f68825a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
