<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__PersonsFloorNo</name>
   <tag></tag>
   <elementGuidId>e3e65af4-5ce7-4d83-b0b7-fe7ab73e9cc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PersonsFloorNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PersonsFloorNo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1c4627b1-ea14-4b31-9f06-9349115837ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>60c5f36a-435f-4b81-b226-2ef6b33c900f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PersonsFloorNo</value>
      <webElementGuid>c609bbe7-be80-4bc5-8b59-93a23c391c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PersonsFloorNo</value>
      <webElementGuid>3840041c-9f20-4df5-9c29-6ed627100827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>رقم الدور</value>
      <webElementGuid>58e4cb44-df64-4aed-9276-39888968cb4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>66a03da5-4090-4976-bab2-c3882ed8a9a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PersonsFloorNo&quot;)</value>
      <webElementGuid>f417df7c-8164-4a70-bf14-1bad74e8324a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PersonsFloorNo']</value>
      <webElementGuid>c8e9f400-a657-41ce-ad00-514ef572ef60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Persons']/div[7]/input</value>
      <webElementGuid>61585427-9b3a-4494-afb9-c589c0bd76ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>252645f3-f42c-48bf-9ff7-f46bba400a9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PersonsFloorNo' and @name = 'PersonsFloorNo' and @placeholder = 'رقم الدور' and @type = 'text']</value>
      <webElementGuid>649650ce-5de9-4d17-a7f0-1cf45afce838</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
