<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__Subject</name>
   <tag></tag>
   <elementGuidId>90151ec6-c1db-47af-a38d-cee3440d8e18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Subject</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Subject']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c47ebc40-4eb1-4713-a3d2-401645202bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4d37d709-8e11-4c73-b0d6-46a94630003d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>36f4233f-179a-4856-8a6e-319ea84b30e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4ccbafc5-1e27-42f4-a68c-66c33426a684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>من فضلك ادخل موضوع الشكوي</value>
      <webElementGuid>5d4f9ed8-8e4c-4f54-be0a-d585dcc1886f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Subject</value>
      <webElementGuid>bdf6554a-1ce7-451b-ba40-28a58bf104a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Subject</value>
      <webElementGuid>9cf99cfc-eb15-43fa-8370-073272516271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ادخل موضوع الشكوي</value>
      <webElementGuid>a8d62b2d-5e20-4293-a033-d29b7b01fdc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>5c52303d-a7ef-4807-bdd6-1c6f57563847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Subject&quot;)</value>
      <webElementGuid>4c943c72-39f3-48d3-b3a3-7b2525305153</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Subject']</value>
      <webElementGuid>d6f4f6ab-0254-43d9-9ec1-b08e7a02f042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/div/form/div[10]/textarea</value>
      <webElementGuid>61c1eafc-a75e-41b0-a036-6b1768fa4daa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>0c5cdbe5-c279-449c-a23f-c8768e242ca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Subject' and @name = 'Subject' and @placeholder = 'ادخل موضوع الشكوي']</value>
      <webElementGuid>892fca6b-6cad-4ad0-8ef6-8732fca21fc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
